export enum ExceptionCodes {
  USER_NOT_FOUND = 1,
  INVALID_PASSWORD = 2,
  PASSWORD_TOO_SHORT = 3,
  ENTITY_NOT_FOUND = 4,
  BAD_REQUEST = 5,
  UNAUTHORIZED = 6,
  POST_NOT_FOUND = 7,
  UNPROCESSABLE_ENTITY = 8,
  INTERNAL_SERVER_ERROR = 9,
  UNKNOWN = 999,
}
